#!/bin/bash
### set up toolshed
if [ ! -d ~/shed ]; then
  /setup_shed
fi
TEMP_LOG_FILE=~/toolshed.log
> "$TEMP_LOG_FILE"
nohup ~/shed/galaxyproject-galaxy/run_tool_shed.sh &> "$TEMP_LOG_FILE" & 
LASTPID=$!
cat << .
   Your toolshed is running as process ID $LASTPID
     - When it is up it will be listening on port 9009 unless 
       you invoked /setup_shed with the --port argument.
     - To see the toolshed log:
         tail -f $TEMP_LOG_FILE
     - Killing the toolshed process tree
         - either run:
             /kill_tree --pid $LASTPID
         - or, equivalently, run:
            kill -TERM -$( \
              ps -a -o pid,pgid \
              | sed -n -e "/^[ ]*$LASTPID[ ]/ { s/.* \([0-9][0-9]*\)[ ]*$/\1/; p; }" \
            )
.
# vim: ts=2 sw=2 et ai:


