#!/bin/bash
PLANEMOPARMS="$*"
usage ()
{
  echo '
  Usage: /run_planemo_serve [optional parameters to be passed through to "planemo serve"]
   e.g.: /run_planemo_serve --port 9090
     or: /run_planemo_serve 
  Take the toolshed name from ~/.planemo.yml
  If you do not supply the port argument, "planemo serve" will listen on port 9090 by default.
  '
}
if [ $1_ == --help_ ]; then
  usage
  exit 0
fi
TEMP_LOG_FILE=~/planemoserve.log
planemo serve \
  $PLANEMOPARMS \
  --host 0.0.0.0 \
  --conda_dependency_resolution \
  . \
  &> "$TEMP_LOG_FILE" & 
LASTPID=$!
cat << .
   'planemo serve' is running as process ID $LASTPID
     - When it is up it will be listening on port 9090 unless 
       you invoked /run_planemo_serve with the --port argument.
     - To see the 'planemo serve' log:
             tail -f $TEMP_LOG_FILE
     - You can shut down 'planemo serve' with the command:
             /kill_tree --pid $LASTPID
         - or, equivalently, run:
             kill -TERM -$( \
               ps -a -o pid,pgid \
               | sed -n -e "/^[ ]*$LASTPID[ ]/ { s/.* \([0-9][0-9]*\)[ ]*$/\1/; p; }" \
             )
.
# vim: ts=2 sw=2 et ai:

