#!/bin/bash
### set up toolshed
if [ ! -d ~/shed ]; then
  mkdir ~/shed
fi
cd ~/shed
TARBALLURL=$( curl --silent https://api.github.com/repos/galaxyproject/galaxy/tags | grep tarball_url | head -n 1 | sed -e 's/.*https:/https:/; s/".*$//;' )
EXPECTED=$( echo $TARBALLURL | sed -e 's/.*[/]//' )
if [ -f $EXPECTED ]; then
  rm $EXPECTED
fi
if [ ! -f $EXPECTED.tgz ]; then
  echo downloading tarball: $TARBALLURL
  wget $TARBALLURL
  mv $EXPECTED $EXPECTED.tgz
  tar xzf $EXPECTED.tgz
fi
if [ -d galaxyproject-galaxy-* ]; then
  mv galaxyproject-galaxy-* galaxyproject-galaxy
fi
TOOLSHEDYML=~/shed/galaxyproject-galaxy/config/tool_shed.yml
if [ ! -f $TOOLSHEDYML ]; then
  # spacing here is critical - no extra spaces or tabs permitted
  sed -e 's/http: 127.0.0.1:\([0-9]*\)/http: 0.0.0.0:\1/' $TOOLSHEDYML.sample > $TOOLSHEDYML
  grep 'static-map: static=static' $TOOLSHEDYML || sed -i -e '/uwsgi:/ {
  # do not change indentation here - it is critical to YAML format
  s/$/\
  static-map: \/static=static/
  }' $TOOLSHEDYML
  grep 'static-map: static\/style=static' $TOOLSHEDYML || sed -i -e '/uwsgi:/ {
  # do not change indentation here - it is critical to YAML format
  s/$/\
  static-map: \/static\/style=static\/style\/blue/
  }' $TOOLSHEDYML
fi

# vim: ts=2 sw=2 et ai:
