#!/bin/bash
## # /setup_homeshed - Script to set up home directory and toolshed
## This script will:
## - set up your home directory
## - initialize (but not start) a Galaxy tool shed
## - will 
## ## Required environment variable:
## - `SHED_URL` - URL for the 'localshed' toolshed
##   - Try to ensure that this URL will resolve in both the container and in a user's web browser
## ## Optional environment variables:
## - `PREFIX` - all but the last two digits of the port numbers on which listeners will listen
## - `SHED_USERNAME` - ID for user in the 'localshed' toolshed
## - `SHED_USEREMAIL` - email for user in the 'localshed' toolshed
## - `SHED_PORT` - PORT for the 'localshed' toolshed
##   - Try to ensure that this PORT will be the same in both the container and in a user's web browser
## - `SHED_ROOT` - directory for installing the 'localshed' toolshed (must not exist)
## - `PLANEMO_SERVE_PORT` - PORT for connecting to web server for 'planemo serve'
## - `PLANEMO_SERVE_PORT` - PORT for connecting to web server for 'planemo shed_serve'

# To rewrite the header of this as markdown, run `sed -n -e '/^##/ !d; /./!d; s/^## //; s/^##$//; p' setup_homeshed`

# SHED_ROOT - directory for installing the 'localshed' toolshed (must not exist)
SHED_ROOT=${SHED_ROOT:-~/shed}
if [ -d $SHED_ROOT ]; then
  echo Directory $SHED_ROOT exists.
  echo Please either delete it or set the SHED_ROOT environment variable to point elsewhere.
  exit 1
fi

# SHED_URL - URL for the 'localshed' toolshed
#   - Try to ensure that this URL will resolve in both the container and in a user's web browser
SHED_URL=${SHED_URL:?http://your.server.fqdn}

# PREFIX - all but the last two digits of the port numbers on which listeners will listen
PREFIX=${PREFIX:-99}

# SHED_USERNAME - ID for user in the 'localshed' toolshed
SHED_USERNAME=${SHED_USERNAME:-demouser}

# SHED_USEREMAIL - email for user in the 'localshed' toolshed
SHED_USEREMAIL=${SHED_USEREMAIL:-demouser@example.net}

# SHED_PORT - PORT for the 'localshed' toolshed
#   - Try to ensure that this PORT will be the same in both the container and in a user's web browser
SHED_PORT=${SHED_PORT:-${PREFIX}88}

# PLANEMO_SERVE_PORT - PORT for connecting to web server for 'planemo serve'
PLANEMO_SERVE_PORT=${PLANEMO_SERVE_PORT:-${PREFIX}90}

# PLANEMO_SERVE_PORT - PORT for connecting to web server for 'planemo shed_serve'
PLANEMO_SHED_SERVE_PORT=${PLANEMO_SHED_SERVE_PORT:-${PREFIX}89}

# set up the home directory on the guest
/setup_home

# persist some info in environmental variables on the guest
echo "
  export PLANEMO_SERVE_PORT=${PLANEMO_SERVE_PORT}
  export PLANEMO_SHED_SERVE_PORT=${PLANEMO_SHED_SERVE_PORT}
  export SHED_PORT=${SHED_PORT}
  export SHED_URL=${SHED_URL}
  export SHED_USERNAME=${SHED_USERNAME}
  export SHED_USEREMAIL=${SHED_USEREMAIL}
  export SHED_ROOT=${SHED_ROOT}
  cat /home/rstudio/.bashrc.d/rstudio | grep -v bashrc 1>&2
" > ~/.bashrc.d/rstudio

# set up a local tool shed
/setup_shed -r ${SHED_ROOT} -p ${SHED_PORT} -a ${SHED_USEREMAIL} -s ${SHED_USERNAME}

# vim: sw=2 ts=2 et :
