#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

testSeedHome() {
  (
     cd $SCRIPTPATH
     if [ -f image ]; then
       . image
     else
       . image.example
     fi
     cd ../build
     $DOCKER build -t devplan .
  )
  IMAGE_BUILD_RESULT=$?
  assertEqual 0 $IMAGE_BUILD_RESULT
  if [ 0 -eq $IMAGE_BUILD_RESULT ]; then
    (
       cd $SCRIPTPATH
       if [ -d image-home ]; then rm -rf image-home; fi
       # redirect stderr to pipe - ref: https://stackoverflow.com/a/2342841
       #  e.g.: (echo something 1>&2) 2>&1 >/dev/null | grep 'something'
       (
         if [ -f image ]; then
           . image
         else
           . image.example
         fi
         ./devplan_bootstrap
       ) 2>&1 >/dev/null | tee image-seedhome-result.txt
    )
    BOOTSTRAP_RESULT=$?
    assertEqual 0 $BOOTSTRAP_RESULT
    if [ 0 -eq $BOOTSTRAP_RESULT ]; then
      assertEqual 1 `grep 'Successfully installed.* planemo-' ${SCRIPTPATH}/image-seedhome-result.txt  | wc -l`
      assertEqual 1 `grep demouser ${SCRIPTPATH}/image-home/shed/galaxyproject-galaxy/config/tool_shed.yml  | wc -l`
      assertEqual 1 `grep demouser ${SCRIPTPATH}/image-home/.planemo.yml  | wc -l`
    fi
  fi
}

# run the tests
source $SCRIPTPATH/bashunit.bash

# vim: sw=2 ts=2 et :
